package com.fazlaka.app.analytics

object Screens {
    const val HOME = "home"
    const val SEASONS = "seasons"
    const val SEASON_DETAIL = "season_detail"
    const val SEARCH = "search"
    const val PROFILE = "profile"
    const val EDIT_PROFILE = "edit_profile"
    const val EPISODE_DETAIL = "episode_detail"
    const val ARTICLE = "article"
    const val PLAYLIST = "playlist"
    const val PLAYLIST_DETAIL = "playlist_detail"
    const val MESSAGES = "messages"
    const val CONVERSATION = "conversation"
    const val NOTIFICATIONS = "notifications"
    const val FRIENDS = "friends"
    const val SETTINGS = "settings"
    const val SECURITY = "security"
    const val SUPPORT = "support"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val FORGOT_PASSWORD = "forgot_password"
    const val RESET_PASSWORD = "reset_password"
    const val VERIFY_EMAIL = "verify_email"
    const val PHONE_AUTH = "phone_auth"
    const val TWO_FACTOR = "two_factor"
    const val SPLASH = "splash"
    const val ALL_EPISODES = "all_episodes"
    const val USER_PROFILE = "user_profile"
}
